# TODO clean config file and add groups

clim_feats:
  - clim_clake
  - clim_ldepth
  - clim_ctype
  - clim_cell_area
  - clim_landsea
  - clim_glm
  - clim_cu
  - clim_cvh
  - clim_cvl
###
  # - clim_tvh
  # - clim_tvl
  # - clim_sotype
###
  - clim_geopot
  - clim_sdfor
  - clim_sdor
  - clim_theta_cap
  - clim_theta_pwp
  - clim_veg_covh
  - clim_veg_covl
  - clim_veg_z0mh
  - clim_veg_z0ml
  - clim_veg_rsminh
  - clim_veg_rsminl

dynamic_feats:
  - met_ctpf
  - met_lwdown
  - met_psurf
  - met_qair
  - met_rainf
  - met_swdown
  - met_snowf
  - met_tair
  - met_wind_e
  - met_wind_n
  - lai_hv
  - lai_lv

targets_prog:
  - swvl1
  - swvl2
  - swvl3
  - stl1
  - stl2
  - stl3
  - snowc
  - aco2gpp
  - dis
  - e
  - sro
  - ssro
#  - rsn
#  - sd
#  - tsn
#  - es

targets_diag:
  - d2m
  - t2m
  - skt
  - sshf
  - slhf

# file_path: "/ec/res4/hpcperm/daep/ecland_i6aj_o400_2010_2022_6hr.zarr"
# file_path: "/ec/res4/hpcperm/daep/ecland_i8ki_o200_2010_2022_1hr.zarr"
# file_path: "/ec/res4/hpcperm/daep/ecland_i6aj_o400_2010_2022_6hr_subset.zarr"
# file_path: "/ec/res4/scratch/daep/ec_training_db_out_O400/ecland_i6aj_2010_2022_6H.zarr"
# file_path: "/ec/res4/scratch/daep/ec_training_db_out_O200/ecland_i8ki_2010_2022_6H.zarr"
# file_path: "/ec/res4/scratch/daep/ec_training_db_out_O200/ecland_i8ki_2010_2022_6H.zarr"
# file_path: "/ec/res4/hpcperm/daep/ec_land_training_db/ecland_i8ki_2010_2022_6h.zarr"
# file_path: "/ec/res4/scratch/daep/ec_training_db_out_O400/ecland_i6aj_2010_2022_6h.zarr"
file_path: "/home/ssd4tb/shams/ecland/ecland_i6aj_o400_2010_2022_6h_euro.zarr"
#file_path: "/home/ssd4tb/shams/ecland/ecland_i8ki_o200_2010_2022_6h.zarr"

training_start: 2010
training_end: 2019

validation_start: 2020
validation_end: 2020

test_start: 2021
test_end: 2022

# x_slice_indices:
#   - 31294
#   - 32294
x_slice_indices:
  - 0
  - None

roll_out: 1  # 8  # 6  # 1
is_add_lat_lon: True
is_norm: True
point_dropout: 0.
random_seed: 0

graph_type: 'distance-graph'
d_graph: 100
k_graph: 8
max_num_points: 8

model: 'GAT'

batch_size: 1  # 2  # 2  # 4  # 8  # 32
num_workers: 8  # 8
hidden_dim: 172  # 64  # 128  # 172  # 128  # 92  # 64  # 164  # 128  #90  # 96  # 120
dropout: 0.15
n_epochs: 100
pin_memory: True
persistent_workers: False
devices: "0"

optimizer: "Adam"
lr: 0.001
weight_decay: 0.0001
beta1: 0.9
beta2: 0.999
lr_scheduler: "cosine"
lr_warmup: 0.00001
lr_warmup_epochs: 2
lr_min: 0.0001
lr_decay_step: 20
lr_decay_rate: 0.9

pretrained: "None"

logging:
  location: "../log"
  name: "GAT"