#
# This file contains required configurations for running the evaluation scipts.
#

# Data storage paths:
path_ec_glob: "/data/ecland_i8ki_o200_2010_2022_6h.zarr"
path_ec_euro: "/data/ecland_i6aj_o400_2010_2022_6h_euro.zarr"


# Inference data paths:
inf_paths:
  xgb_v1: "/data/ch23/data_ch23/xgbosst_train_2010_2019_val_2020_2020_est_50_hist.zarr"
  xgb_diag_v2: "/data/ch23/data_ch23/euro_xgb_train_2010_2019_val_2020_2020_diagnostic_v2.zarr"
  xgb_v3: "/data/ch23/data_ch23/euro_xgb_train_2010_2019_val_2020_2020.zarr"
  mlp_v1: "/data/ch23/data_ch23/euro_mlp_train_2010_2019_val_2020_2020.zarr"
  mlp_v2: "/data/ch23/data_ch23/euro_mlp_v2_train_2010_2019_val_2020_2020.zarr"
  mlp_v3: "/data/ch23/data_ch23/euro_mlp_v3_train_2010_2019_val_2020_2020.zarr"
  unimp_v1: "/data/ch23/data_ch23/euro_unimp_train_2010_2019_val_2020_2020.zarr"
  unimp_v2: "/data/ch23/data_ch23/euro_unimp_v2_train_2010_2019_val_2020_2020.zarr"
  unimp_v3: "/data/ch23/data_ch23/euro_unimp_v3_train_2010_2019_val_2020_2020.zarr"
  mamba_v1: "/data/ch23/data_ch23/euro_mamba_v1_train_2010_2019_val_2020_2020.zarr"
  mamba_v2: "/data/ch23/data_ch23/euro_mamba_v2_train_2010_2019_val_2020_2020.zarr"
  mamba_v3: "/data/ch23/data_ch23/euro_mamba_v3_train_2010_2019_val_2020_2020.zarr"
  mamba_v4: "/data/ch23/data_ch23/euro_mamba_v4_train_2010_2019_val_2020_2020.zarr"
  mamba_rollout_32: "/data/ch23/data_ch23/euro_mamba_rollout_32_train_2010_2019_val_2020_2020.zarr"
  mamba_rollout_64: "/data/ch23/data_ch23/euro_mamba_rollout_64_train_2010_2019_val_2020_2020.zarr"
  mlp_obs_v1: "/data/ch23/data_ch23/euro_mlp_obs_without_timevarying_lai_train_2010_2019_val_2020_2020.zarr"
  mlp_obs_v2: "/data/ch23/data_ch23/euro_mlp_v2_obs_without_timevarying_lai_train_2010_2019_val_2020_2020.zarr"
  mlp_obs_lai: "/data/ch23/data_ch23/euro_mlp_obs_with_timevarying_lai_train_2010_2019_val_2020_2020.zarr"


# Evaluation results data paths:
eval_paths:
  xgb_v1: "/data/ch23/evalution_results/xgbosst_train_2010_2019_val_2020_2020_est_50_hist"
  xgb_diag_v2: "/data/ch23/evalution_results/euro_xgb_train_2010_2019_val_2020_2020_diagnostic_v2"
  xgb_v3: "/data/ch23/evalution_results/euro_xgb_train_2010_2019_val_2020_2020"
  mlp_v1: "/data/ch23/evalution_results/euro_mlp_train_2010_2019_val_2020_2020"
  mlp_v2: "/data/ch23/evalution_results/euro_mlp_v2_train_2010_2019_val_2020_2020"
  mlp_v3: "/data/ch23/evalution_results/euro_mlp_v3_train_2010_2019_val_2020_2020"
  unimp_v1: "/data/ch23/evalution_results/euro_unimp_train_2010_2019_val_2020_2020"
  unimp_v2: "/data/ch23/evalution_results/euro_unimp_v2_train_2010_2019_val_2020_2020"
  unimp_v3: "/data/ch23/evalution_results/euro_unimp_v3_train_2010_2019_val_2020_2020"
  mamba_v1: "/data/ch23/evalution_results/euro_mamba_v1_train_2010_2019_val_2020_2020"
  mamba_v2: "/data/ch23/evalution_results/euro_mamba_v2_train_2010_2019_val_2020_2020"
  mamba_v3: "/data/ch23/evalution_results/euro_mamba_v3_train_2010_2019_val_2020_2020"
  mamba_v4: "/data/ch23/evalution_results/euro_mamba_v4_train_2010_2019_val_2020_2020"
  mamba_rollout_32: "/data/ch23/evalution_results/euro_mamba_rollout_32_train_2010_2019_val_2020_2020"
  mamba_rollout_64: "/data/ch23/evalution_results/euro_mamba_rollout_64_train_2010_2019_val_2020_2020"
  mlp_obs_v1: "/data/ch23/evalution_results/euro_mlp_obs_without_timevarying_lai_train_2010_2019_val_2020_2020"
  mlp_obs_v2: "/data/ch23/evalution_results/euro_mlp_v2_obs_without_timevarying_lai_train_2010_2019_val_2020_2020"
  mlp_obs_lai: "/data/ch23/evalution_results/euro_mlp_obs_with_timevarying_lai_train_2010_2019_val_2020_2020"


# Model weight paths for inference:
path_w_xgb_v1: "/home/ch23/weights_ch23/xgb_v1.json"


# Targets as in ML-BEES-train:
targets_prog:
  - swvl1
  - swvl2
  - swvl3
  - stl1
  - stl2
  - stl3
  - snowc

targets_diag:
  - d2m
  - t2m
  - skt
  - sshf
  - slhf
  - aco2gpp
  - dis
  - e
  - sro
  - ssro